spound/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

spound/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from core import views


urlpatterns = [
    path('home/', views.home_view, name='home'),
    path('signin/', views.signin_view, name='signin'),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
]

spound/core/models.py
from django.db import models

spound/core/views.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView

from core.services import SpotifyAuthService, SpotifyService


class SignInView(TemplateView):
    template_name = 'signin.html'

    def get(self, request, *args, **kwargs):
        self.auth_service = SpotifyAuthService()
        self.code = self.auth_service.parse_response_code(request.get_full_path())
        if self.code:
            return redirect(reverse('core:home'))

        return super().get(request, *args, **kwargs)

    def get_context_data(self):
        context = super().get_context_data()
        if not self.code:
            context['auth_url'] = self.auth_service.get_authorize_url()
        return context


signin_view = SignInView.as_view()


class HomeView(TemplateView):
    template_name = 'home.html'

    def get(self, request, *args, **kwargs):
        auth_service = SpotifyAuthService()
        access_token = auth_service.get_access_token()

        if not access_token:
            return redirect(reverse('core:signin'))

        spotify_service = SpotifyService(access_token)
        self.user = spotify_service.current_user()
        self.playlists = spotify_service.current_user_playlists()

        return super().get(request, *args, **kwargs)

    def get_context_data(self):
        context = super().get_context_data()
        context['user'] = self.user,
        context['playlists'] = self.playlists['items'],

        return context


home_view = HomeView.as_view()

spound/frontend/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
  
  <!-- Loading third party fonts -->
  <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900" rel="stylesheet" type="text/css">
  <link href="{% static 'fonts/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  <!-- Loading main css file -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
  <!--[if lt IE 9]>
  <script src="js/ie-support/html5.js"></script>
  <script src="js/ie-support/respond.js"></script>
  <![endif]-->
  <title>Spound - Your jukebox online!</title>
</head>

<body class="{% block body_class %}{% endblock %}">
  
  <div id="site-content">
    {% include '_navbar.html' %}
    {% block content %}{% endblock %}
    {% include '_footer.html' %}
  </div> <!-- #site-content -->

  <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>		
  <script src="{% static 'js/plugins.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

spound/frontend/templates/_footer.html
{% load static %}

<footer class="site-footer">
  <div class="container">
    <img src="{% static 'images/logo-footer.png' %}" alt="Site Name">
    
    <address>
      <p>Sorocaba, SP - Brasil <br>
        <a href="tel:9999999999999">+5599999999999</a> <br>
        <a href="#">info@spound.com</a>
      </p> 
    </address> 
    
    <form action="#" class="newsletter-form">
      <input type="email" placeholder="Enter your email to join newsletter...">
      <input type="submit" class="button cut-corner" value="Subscribe">
    </form> <!-- .newsletter-form -->
    
    <div class="social-links">
      <a href="#"><i class="fa fa-facebook-square"></i></a>
      <a href="#"><i class="fa fa-twitter"></i></a>
      <a href="#"><i class="fa fa-google-plus"></i></a>
      <a href="#"><i class="fa fa-pinterest"></i></a>
    </div> <!-- .social-links -->
    
    <p class="copy">Copyright 2018 Spound.</p>
  </div>
</footer> <!-- .site-footer -->

spound/frontend/templates/_navbar.html
{% load static %}

<header class="site-header">
  <div class="container">
    <a href="{% url 'core:index' %}" id="branding">
      <img src="{% static 'images/logo.png' %}" alt="Site Title">
      <small class="site-description">Your jukebox online.</small>
    </a> <!-- #branding -->
    
    <nav class="main-navigation">
      <button type="button" class="toggle-menu"><i class="fa fa-bars"></i></button>
      <ul class="menu">
        <li class="menu-item"><a href="{% url 'core:signin' %}">Sign In</a></li>
      </ul> <!-- .menu -->
    </nav> <!-- .main-navigation -->
    <div class="mobile-menu"></div>
  </div>
</header> <!-- .site-header -->

spound/frontend/templates/home.html
{% extends '_base.html' %}


{% block content %}
<main class="main-content">
  <div class="container">
    <div class="content fullwidth">
      <h2 class="page-title">This is home page.</h1>
    </div>
  </div>
</main>
{% endblock %}

spound/frontend/templates/index.html
{% extends '_base.html' %}

{% load static %}

{% block body_class %}header-collapse{% endblock %}

{% block content %}
<div class="hero">
  <div class="slider">
    <ul class="slides">
      <li class="lazy-bg" data-background="{% static 'images/slide-1.jpg' %}">
        <div class="container">
          <h2 class="slide-title">Spound</h2>
          <h3 class="slide-subtitle">Your jukebox online!</h3>
          <p class="slide-desc">Make your parties and events even better. Let's Spound help you and your friends creating the best music playlist.</p>

          <a href="#" class="button cut-corner">Create your event</a>
        </div>
      </li>
      <li class="lazy-bg" data-background="{% static 'images/slide-2.jpg' %}">
        <div class="container">
            <h2 class="slide-title">Everyone is a DJ</h2>
            <h3 class="slide-subtitle">Collaborative playlists</h3>
            <p class="slide-desc">Spound makes easier and funnier to build and to manage collaborative playlists. Improve the experience of all your guests.</p>

            <a href="#" class="button cut-corner">Create your event</a>
        </div>
      </li>
      <li class="lazy-bg" data-background="{% static 'images/slide-3.jpg' %}">
        <div class="container">
            <h2 class="slide-title">Discover new Experiences</h2>
            <h3 class="slide-subtitle">An unexpected journey to each song</h3>
            <p class="slide-desc">Every party turns a lot better and unexpected when everyone helps to build the song atmosphere. Let's rock!</p>

            <a href="#" class="button cut-corner">Create your event</a>
        </div>
      </li>
    </ul>
  </div>
</div>

<main class="main-content">
  <div class="fullwidth-block testimonial-section">
    <div class="container">
      <div class="quote-slider">
        <ul class="slides">
          <li>
            <blockquote>
              <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo"</p>
              <cite>John Smith</cite>
              <span>Corporation CEO, books author</span>
            </blockquote>
          </li>
          <li>
            <blockquote>
              <p>"Iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo"</p>
              <cite>John Smith</cite>
              <span>Corporation CEO, books author</span>
            </blockquote>
          </li>
        </ul>
      </div>
    </div>
  </div> <!-- .testimonial-section -->

  <div class="fullwidth-block upcoming-event-section" data-bg-color="#191919">
    <div class="container">
      <header class="section-header">
        <h2 class="section-title">Recent Spound events</h2>

        <div class="event-nav">
          <a class="prev" id="event-prev" href="#"><i class="fa fa-caret-left"></i></a>
            <a class="next" id="event-next" href="#"><i class="fa fa-caret-right"></i></a>
        </div> <!-- .event-nav -->

      </header> <!-- .section-header -->
      <div class="event-carousel">
        
        <div class="event">
          <div class="entry-date">
            <div class="date">23</div>
            <span class="month">Jun</span>
          </div>
          <h2 class="entry-title"><a href="#">Sed et persipiatis unde omnis iste natus</a></h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid temporibus quos aspernatur</p>
        </div> <!-- .event -->
        
        
        <div class="event">
          <div class="entry-date">
            <div class="date">23</div>
            <span class="month">Jun</span>
          </div>
          <h2 class="entry-title"><a href="#">Sed et persipiatis unde omnis iste natus</a></h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid temporibus quos aspernatur</p>
        </div> <!-- .event -->
        
        
        <div class="event">
          <div class="entry-date">
            <div class="date">23</div>
            <span class="month">Jun</span>
          </div>
          <h2 class="entry-title"><a href="#">Sed et persipiatis unde omnis iste natus</a></h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid temporibus quos aspernatur</p>
        </div> <!-- .event -->
        
        
        <div class="event">
          <div class="entry-date">
            <div class="date">23</div>
            <span class="month">Jun</span>
          </div>
          <h2 class="entry-title"><a href="#">Sed et persipiatis unde omnis iste natus</a></h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid temporibus quos aspernatur </p>
        </div> <!-- .event -->
        
        
        <div class="event">
          <div class="entry-date">
            <div class="date">23</div>
            <span class="month">Jun</span>
          </div>
          <h2 class="entry-title"><a href="#">Sed et persipiatis unde omnis iste natus</a></h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid temporibus quos aspernatur </p>
        </div> <!-- .event -->
        
      </div> <!-- .event-carousel -->
    </div> <!-- .container -->
  </div> <!-- .upcoming-event-section -->

</main> <!-- .main-content -->
{% endblock %}

spound/frontend/templates/signin.html
{% extends '_base.html' %}


{% block content %}
<main class="main-content">
  <div class="container">
    <div class="content fullwidth">
      <h2 class="page-title">Authorize Spotify</h2>
      <a class="button primary" href="{{ auth_url }}">Authorize Spotify...</a>
    </div>
  </div>
</main>
{% endblock %}